name: flutter_application_1
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\tree.jpg
    - assets\home\foodie_logo.png
    - assets\home\images\41.png
    - assets\home\images\351.png
    - assets\home\promo\promo1.png
    - assets\home\promo\promo2.png
    - assets\home\promo\promo3.png
    - assets\home\promo\promo4.png
    - assets\home\promo\promo5.png
    - assets\home\promo\promo6.png
    - assets\home\boba.png
    - assets\home\machi.png
